name: yanglingling
age : 24
#等价于header :order
header: '{cipher}2da99ae578e680e234ee3779aa5ca955257260302ad93ccac5c97244d7f4929a'

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/

spring:
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/public?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root